name: Test and Lint on push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run lint check
        run: ./gradlew lint

      - uses: actions/upload-artifact@v2
        with:
          name: lint-report.html
          path: app/build/reports/lint-results.html

      - name: Run lint check
        run: ./gradlew lint

      - uses: actions/upload-artifact@v2
        with:
          name: test-results.html
          path: "*/build/reports/lint-results.html"

      - name: Run tests
        run: ./gradlew test

      - uses: actions/upload-artifact@v2
        with:
          name: test-results.html
          path: "*/build/reports/tests/testDebugUnitTest/**"
